### PR TITLE
Dalton crud setup

### PR DESCRIPTION
**Pull request by Dalton-Kujawa**
Hey Guys, I got the code working finally! After merging with main everything works and I have my tables setup in a file so you can add the table as needed.

### CODE REVIEW

**Comment by Dalton-Kujawa** [comment]
Step1
To test start by going to blogs
You should see your table of contents shown (which will be nothing if you just start with no table data)
Next got to new blog and type in the needed info
You should be redirected back to blogs home and see your added table data
next click on the data you just added to access the details of it 
Step2
Next click update to then update with new info
Step2-Delete
it should redirect you back to the details of that page with the new info, now press the delete button!

**Comment by LaplacesAngel** [comment]
Good work man! A lot of that works, I'm having some issues which might just be because of my table structure when I run it.

When I create a new blog it doesn't have a BlogID, might just be because I have a different table name? I changed all instances of blogs to my table name "newtowndogs" in index.js. E.G. 
// Blog Functions!
app.get("/api/data", async (req, res) => {
  await read(req, res, "SELECT * FROM newtowndogs");
});
image


makes reading work but when I click on the newly created blog I get this:
image

If I manually insert a Blog ID using mysql I can then get the edit and delete screens.
image


Delete works at that point. However Edit leaves me unable to change anything.
image

**Comment by Dalton-Kujawa** [comment]
Actually the table name will have to be blogs for sure.

**Comment by Dalton-Kujawa** [comment]
Or atleast if you changed the names in index.js it should just work from then on

**Comment by LaplacesAngel** [comment]
Nice, I got farther creating a table called blogs but still can't edit but should be fine, will approve now, awesome functionality man!

**Review by LaplacesAngel — APPROVED** [review]
good wooork

**Pull request merged**
